AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Lambda Function that scape the news feeds and update the database
Resources:
  AspNetCoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: "SpaceNews.Lambda::SpaceNews.Lambda.Function::FunctionHandler"
      Runtime: dotnet8
      CodeUri: ''
      MemorySize: 512
      Timeout: 120
      Role: null
      Policies:
        - AWSLambda_FullAccess
      Environment:
        Variables:
          DB_CONNECTION_STRING: "{{resolve:ssm:/SpaceNews/DatabaseConnectionString}}"
      Events:
        InvocationLevel:
          Type: Schedule
          Properties: 
            Schedule: cron(30 05 * * ? *)