AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: An AWS Serverless Application that uses the ASP.NET Core framework running
  in Amazon Lambda.
Parameters:
  DBConnectionString:
    Description: Database ConnectionString
    Type: String
  AllowedOrigin:
    Description: API ALlowed Origin
    Type: String
Resources:
  AspNetCoreFunction:
    Type: AWS::Serverless::Function
    Properties:
      Handler: SpaceNews.API
      Runtime: dotnet8
      CodeUri: ''
      MemorySize: 512
      Timeout: 30
      Role: null
      Policies:
        - AWSLambda_FullAccess
      Environment:
        Variables:
          DB_CONNECTION_STRING: !Ref DBConnectionString
          ALLOWED_ORIGIN: !Ref AllowedOrigin
      Events:
        ProxyResource:
          Type: HttpApi
          Properties:
            Path: /{proxy+}
            Method: ANY
        RootResource:
          Type: HttpApi
          Properties:
            Path: /
            Method: ANY
Outputs:
  ApiURL:
    Description: API endpoint URL for Prod environment
    Value: !Sub 'https://${ServerlessHttpApi}.execute-api.${AWS::Region}.amazonaws.com/'
